[package]
name = "web"
version = "0.1.1"
edition = "2021"

[dependencies]
dioxus = { workspace = true, features = ["fullstack"] }
dioxus-logger.workspace = true
ui = { workspace = true }

[features]
default = []
web = ["dioxus/web", "ui/web"]
server = ["dioxus/server", "ui/server"]
