[package]
name = "desktop"
version = "0.1.0"
edition = "2021"

[dependencies]
dioxus = { workspace = true, features = ["router", "desktop"] }
dioxus-logger.workspace = true
ui = { workspace = true, features = ["dioxus-desktop"] }

[features]
default = []
desktop = ["dioxus/desktop"]
server = ["dioxus/server"]

[[bin]]
name = "neptune-gui"
path = "src/main.rs"
