[application]
name = "neptune-proton" # Replace with your application's name
product_name = "Neptune Proton" # A more user-friendly name, optional
version = "0.1.0" # Your application's version
# For a desktop app, the `main_binary` should point to the name of your crate's binary
# If your desktop crate is named `desktop`, and it produces a binary `desktop`, use that.
main_binary = "neptune-proton" # This should match the name of the executable produced by your desktop crate


[bundle]
identifier = "cash.neptune"
publisher = "neptune.cash"

icon = [
    "icons/logo-128x128.png", 
    "icons/logo-1024x1024.png", 
    "icons/icon.ico", 
]
